#!/usr/bin/env sh

# Format Python files (only if Python files are in staging)
./scripts/format-python.sh

# Format Go files
cd libs/go-hello-libs && go fmt ./... && cd ../../
cd apps/go-hello && go fmt ./... && cd ../../

# Format Java and XML files
./scripts/format-java.sh

# Run lint-staged
npx lint-staged
