#!/usr/bin/env sh

# Format Python files
nx run-many --target=format --projects=python-hello,python-hello-libs

# Format Go files
cd libs/go-hello-libs && go fmt ./... && cd ../../
cd apps/go-hello && go fmt ./... && cd ../../

# Run lint-staged
npx lint-staged
