name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: bash -l {0}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install SDKMAN and Java tools
      - name: Install SDKMAN and Java tools
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 21.0.2-tem
          sdk use java 21.0.2-tem
          sdk install maven 3.9.9
          sdk use maven 3.9.9
          echo "SDKMAN_DIR=$HOME/.sdkman" >> $GITHUB_ENV
          echo "JAVA_HOME=$HOME/.sdkman/candidates/java/current" >> $GITHUB_ENV
          echo "M2_HOME=$HOME/.sdkman/candidates/maven/current" >> $GITHUB_ENV
          echo "PATH=$HOME/.sdkman/candidates/java/current/bin:$HOME/.sdkman/candidates/maven/current/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      # Set up Java cache
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: Linux-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            Linux-maven-

      # Install google-java-format
      - name: Install google-java-format
        run: |
          curl -L https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar -o google-java-format.jar
          chmod +x google-java-format.jar

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Set up Go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      # Install Go dependencies
      - name: Install Go dependencies
        run: |
          cd libs/go-hello-libs && go mod tidy
          cd ../../apps/go-hello && go mod tidy

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Install xmllint
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      # Format check Java and XML files
      - name: Check Java formatting
        run: |
          find . -name "*.java" -not -path "*/target/*" -exec java -jar google-java-format.jar --set-exit-if-changed {} \;

      - name: Check XML formatting
        run: |
          find . -name "*.xml" -not -path "*/target/*" -exec xmllint --format --output '{}' '{}' \;
          git diff --exit-code

      # Build and test Java projects
      - name: Build and install Java libraries
        run: |
          cd libs/java-hello-libs
          mvn clean install
          cd ../..

      - name: Build and test Java applications
        run: |
          cd apps/java-hello
          mvn clean verify
          cd ../..

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: |
          npx nx affected -t lint test build typecheck
